### ISSUE TITLE
Wrong image shown sometimes

### ISSUE THREAD

**Issue by jmauersberger** [JamaSoftware/RestClient#14] opened 2017-07-20 19:45 UTC
During testing it was observed that sometimes the wrong image is shown. Its not yet fully clear how to reproduce this but I wanted to record this issue. I will try to get a reproduction scenarion soon...

**Comment by ibilal-jama** [comment] 2017-08-15 20:16
This is interesting, and could very well be an issue with how the images are encoded in our system. Please do let me know if you are able to reproduce this issue, and we can troubleshoot to determine the cause of this.

**Comment by ibilal-jama** [comment] 2017-08-23 18:41
Closing for now. If you are able to reproduce this, we can troubleshoot then and dig into this more.

**Closed by ibilal-jama** 2017-08-23 18:41 UTC

**Comment by jmauersberger** [comment] 2020-08-19 19:00
We got this issue reported again and in that case the icon is not just wrong, its wrong in the way that type A shows icon of type B and vice versa. I would like to reopen this ticket and maybe can come up with details.

**Comment by nmchale-jama** [comment] 2020-08-31 20:05
Hello Jan,

We are not actively maintaining this repository at this time.  Furthermore I am unfamiliar with this defect.  If you could provide a more specific example of what is going wrong I may be able to help.  What icon are you referring to?  The item type icon?  Is it loading incorrectly in the Jama Application, or when downloaded via the client?

However, as this is an open source repository and is no longer being maintained by us, I cannot guarantee that we will be able to provide a solution.  

Best Regards,
Nick

**Comment by jmauersberger** [comment] 2020-09-01 12:08
Thanks Nick for the feedback,

its actually the item type icon when downloaded in the client, strangely not wrong but swapped.
Anyway, I got the point that you are not active in this repo.

You still handle pull requests though? if not, is it possible to get write access to the repo at some point in time?

Thanks Jan
